services:
  db: 
    container_name: planer_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planer_db
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/